# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: activityStream
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Reflecting and sharing about software and life. After more than a decade in
  England I returned to my native South Africa in 2014.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: avermeulen
github_username:  avermeulen

# Build settings
markdown: kramdown
